// Copy for the approach cards and the comparison table.

export const APPROACHES = [
	{
		id: 'physical',
		num: 1,
		name: 'Stock PBR',
		kind: 'Real time',
		kindTone: 'live',
		title: 'three.js MeshPhysicalMaterial with glTF iridescence',
		technique: 'Standard rasteriser material: KHR_materials_iridescence (Belcour–Barla thin film) and KHR_materials_sheen, driven by the procedural knit maps (albedo, normal, roughness, occlusion, coating mask, thickness).',
		physics: 'The film colour appears only in the specular reflection. Diffuse light gets a single complementary tint, and only from the environment, not from the spot light.',
		speed: '≈ 2–4 ms per frame on a laptop GPU',
		strengths: 'Exports 1:1 as glTF, so the same material runs in Unity, Unreal, Babylon.js, model-viewer and Blender. Cheapest to render at scale.',
		limits: 'Film index is capped at 2.333 and there is no stacked-platelet gain, so the band reads whiter and flatter than in the photo.',
		useFor: 'Pipelines that must stay glTF-portable: AR viewers, game engines, e-commerce 3D.',
	},
	{
		id: 'spectral',
		num: 2,
		name: 'Spectral layers',
		kind: 'Real time',
		kindTone: 'live',
		title: 'Custom spectral interference shader',
		technique: 'A custom BRDF injected into three.js’ physical pipeline, so shadows, image-based light and tone mapping still work. The film is solved per wavelength (81 samples, s and p polarisation, CIE 1931 observer) and tabulated by angle and thickness.',
		physics: 'Interference reflection × stacked-platelet gain, plus the transmitted complement T(θ_in)·T(θ_out) on the yarn underneath. Where a light mirrors you see violet-magenta, elsewhere cream: the alternation in your photo. Bricks jitter ±12 % in thickness, and stretch thins the film.',
		speed: '≈ 3–5 ms per frame',
		strengths: 'Closest match to the photo. Every physical quantity is a slider (indices, thickness, gain, roughness), which suits domain randomisation and fitting to measurements.',
		limits: 'Single scattering only, no global illumination. It is a custom shader, so other engines need a port (HLSL or Shader Graph).',
		useFor: 'Bulk synthetic data: thousands of lit, posed, stretched views per minute.',
	},
	{
		id: 'diffraction',
		num: 3,
		name: 'Diffraction',
		kind: 'Real time',
		kindTone: 'live',
		title: 'Holographic grating shader',
		technique: 'Grating equation L_t = −V_t + m·λ/Λ. Each order (±1, optionally ±2) and each of 12 wavelength bins fetches the environment from its own direction. Spot and point lights use a Stam-style spectral lobe.',
		physics: 'The competing hypothesis: an embossed holographic foil. Light sources are spread into rainbows whose position depends on groove direction and period. Per-brick orientation gives a “pixel hologram”.',
		speed: '≈ 8–15 ms per frame (24 environment look-ups per pixel)',
		strengths: 'The only approach that produces true spectral streaks under a point light. Groove period and orientation are explicit.',
		limits: 'It does not produce the cream-versus-magenta flop seen in the photo, so it is the right model only if the flashlight test shows rainbows.',
		useFor: 'Use it if the real band turns out to be holographic, or as a hard negative in training.',
	},
	{
		id: 'pathtracer',
		num: 4,
		name: 'Path traced',
		kind: 'Progressive',
		kindTone: 'progressive',
		title: 'GPU path tracer in the browser',
		technique: 'three-gpu-pathtracer (WebGL2): BVH ray tracing, multiple importance sampling of the HDR, a sized spot light, 5 bounces. Its BSDF is patched at build time: the diffuse lobe carries the film transmittance and the film reflection gets the same 1.6× platelet gain as approach 2.',
		physics: 'The same glTF inputs as approach 1, with the layered complement of approach 2 and full light transport: soft shadows, band-to-skin colour bleeding, occlusion inside the bricks.',
		speed: 'Progressive: ≈ 1–5 s to a clean frame on a desktop GPU. Geometry is static while tracing.',
		strengths: 'Ground-truth light transport without leaving the browser. Use it to measure the bias of the real-time approaches.',
		limits: 'Too slow for large datasets. Breathing and flexing animations pause while it converges.',
		useFor: 'Validation sets, and checking that real-time renders are not teaching a model wrong shading.',
	},
	{
		id: 'cycles',
		num: 5,
		name: 'Cycles offline',
		kind: 'Pre-rendered',
		kindTone: 'offline',
		title: 'Blender 5.2 Cycles, layered thin film with micro-displacement',
		technique: 'Same meshes, maps and HDRIs exported from this page’s code. Principled BSDF thin film in a layered node setup (platelet gain plus transmittance ramp), true displacement from a 16-bit height map via adaptive subdivision, OIDN denoising.',
		physics: 'Approach 2’s optics with real geometric relief: the brick recesses shadow and inter-reflect. Cycles evaluates the film with its own implementation, which comes out slightly cooler.',
		speed: '≈ 20 s per frame at 800×500 on 4 CPU cores (about 1–3 s on an RTX-class GPU)',
		strengths: 'Production quality, with mask, depth and normal passes available. A scripted, randomised dataset generator is included.',
		limits: 'Not interactive: here you scrub through 245 pre-rendered frames.',
		useFor: 'Final high-fidelity training and evaluation sets with exact labels.',
	},
];

export const COMPARISON = {
	columns: [ 'Stock PBR', 'Spectral layers', 'Diffraction', 'Path traced', 'Cycles offline' ],
	rows: [
		{ label: 'Colour mechanism', values: [ 'Thin film (RGB fit)', 'Thin film (81 λ, polarised)', 'Grating orders', 'Thin film (RGB fit)', 'Thin film (Cycles)' ] },
		{ label: 'Complementary flop', values: [ 'Partial (environment only)', 'Yes', 'No', 'Yes (patched)', 'Yes (node ramp)' ] },
		{ label: 'Light transport', values: [ 'Direct + IBL', 'Direct + IBL', 'Direct + IBL', 'Global illumination', 'Global illumination' ] },
		{ label: 'Brick relief', values: [ 'Normal map', 'Normal map', 'Normal map', 'Normal map', 'True displacement' ] },
		{ label: 'Deforms live', values: [ 'Yes', 'Yes', 'Yes', 'Static poses', 'Per render' ] },
		{ label: 'Frame cost', values: [ '2–4 ms', '3–5 ms', '8–15 ms', '1–5 s', '20 s (CPU)' ] },
		{ label: 'Match to photo', values: [ 'Low', 'High', 'Low (different look)', 'High', 'High' ], rating: [ 1, 3, 1, 3, 3 ] },
		{ label: 'Portability', values: [ 'Any glTF engine', 'Shader port', 'Shader port', 'Web only', 'Blender' ] },
		{ label: 'Training role', values: [ 'Portable baseline', 'Bulk generator', 'Hypothesis check', 'Validation set', 'Gold set + masks' ] },
	],
};
